# apiVersion: v1
# kind: Secret
# metadata:
#   name: connectors-secret
#   namespace: kafka
# type: Opaque
# data:
#   MASTER_MYSQL_HOSTNAME:  aGVsbG93b3JsZCAtbgo=   # Replace with re-encoded value
#   MASTER_MYSQL_USERNAME:  aGVsbG93b3JsZCAtbgo=                   # Replace with re-encoded value
#   MASTER_MYSQL_PASSWORD:  aGVsbG93b3JsZCAtbgo=      # Replace with re-encoded value
#   REPLICA_MYSQL_HOSTNAME: aGVsbG93b3JsZCAtbgo=  # Replace with re-encoded value
#   REPLICA_MYSQL_USERNAME: aGVsbG93b3JsZCAtbgo=                      # Replace with re-encoded value
#   REPLICA_MYSQL_PASSWORD: aGVsbG93b3JsZCAtbgo=      # Replace with re-encoded value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-source-innovate-secret
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m #1h  # Periodic sync interval
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-source-innovate-secret  # Kubernetes secret name
    namespace: kafka
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: source-innov8-mysql
      property: user
  - secretKey: password
    remoteRef:
      key: source-innov8-mysql
      property: password
  - secretKey: host
    remoteRef:
      key: source-innov8-mysql
      property: host
  - secretKey: database
    remoteRef:
      key: source-innov8-mysql
      property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-sink-innovate-secret
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m #1h  # Periodic sync interval
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-sink-innovate-secret  # Kubernetes secret name
    namespace: kafka
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: destination-innov8-mysql
      property: user
  - secretKey: password
    remoteRef:
      key: destination-innov8-mysql
      property: password
  - secretKey: host
    remoteRef:
      key: destination-innov8-mysql
      property: host
  - secretKey: database
    remoteRef:
      key: destination-innov8-mysql
      property: database

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-source-loyalty-secret
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m #1h  # Periodic sync interval
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-source-loyalty-secret  # Kubernetes secret name
    namespace: kafka
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: source-loyalty-mysql
      property: user
  - secretKey: password
    remoteRef:
      key: source-loyalty-mysql
      property: password
  - secretKey: host
    remoteRef:
      key: source-loyalty-mysql
      property: host
  - secretKey: database
    remoteRef:
      key: source-loyalty-mysql
      property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-sink-loyalty-secret
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m #1h  # Periodic sync interval
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-sink-loyalty-secret  # Kubernetes secret name
    namespace: kafka
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: destination-loyalty-mysql
      property: user
  - secretKey: password
    remoteRef:
      key: destination-loyalty-mysql
      property: password
  - secretKey: host
    remoteRef:
      key: destination-loyalty-mysql
      property: host
  - secretKey: database
    remoteRef:
      key: destination-loyalty-mysql
      property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-source-ni-secret
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m #1h  # Periodic sync interval
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-source-ni-secret  # Kubernetes secret name
    namespace: kafka
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: source-ni-mysql
      property: user
  - secretKey: password
    remoteRef:
      key: source-ni-mysql
      property: password
  - secretKey: host
    remoteRef:
      key: source-ni-mysql
      property: host
  - secretKey: database
    remoteRef:
      key: source-ni-mysql
      property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-sink-ni-secret
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m #1h  # Periodic sync interval
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-sink-ni-secret  # Kubernetes secret name
    namespace: kafka
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: destination-ni-mysql
      property: user
  - secretKey: password
    remoteRef:
      key: destination-ni-mysql
      property: password
  - secretKey: host
    remoteRef:
      key: destination-ni-mysql
      property: host
  - secretKey: database
    remoteRef:
      key: destination-ni-mysql
      property: database

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["mysql-sink-innovate-secret","mysql-source-innovate-secret","mysql-sink-ni-secret","mysql-source-ni-secret","mysql-sink-loyalty-secret","mysql-source-loyalty-secret"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
- kind: ServiceAccount
  name: kafka-connect-cluster-connect
  namespace: kafka
roleRef:
  kind: Role
  name: connector-configuration-role
  apiGroup: rbac.authorization.k8s.io