apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.10.x
      helm:
        releaseName: schema-registry
        valueFiles:
        - "$values/kubernetes/argocd-helmcharts/values/external-secrets-operator-values.yaml"
    - repoURL: 'https://github.com/elissiafellow/dataops-dms2.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - Validate=true
      - CreateNameSpace=true
      - PruneProgationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false # whether to ignore differences while syncing or not, used when explicitly use ignoredifference feature