apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/tracking-id: "kafka-cluster:argoproj.io/Application:argocd/kafka-cluster"
spec:
  project: default
  source:
    repoURL: 'https://github.com/elissiafellow/dataops-dms2.git'
    targetRevision: main
    path: kubernetes/production/kafka-raft/kafka-seperate/main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka # removing the default namespace trying to ignore the clusterrolebinding outofsync
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - Validate=true
      - CreateNameSpace=true
      - PruneProgationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false # whether to ignore differences while syncing or not, used when explicitly use ignoredifference feature
