apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  sources:
    - chart: schema-registry
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 22.0.0 
      helm:
        releaseName: schema-registry
        valueFiles:
          - "$values/kubernetes/argocd-helmcharts/values/schema-registry-values.yaml"
    - repoURL: 'git@github.com:elissiafellow/dataops-dms2.git'
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - Validate=true
      - CreateNameSpace=true
      - PruneProgationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false # whether to ignore differences while syncing or not, used when explicitly use ignoredifference feature
