apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: 'https://github.com/elissiafellow/dataops-dms2.git'
    targetRevision: main
    path: kubernetes/production/schema-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - Validate=true
      - CreateNameSpace=true
      - PruneProgationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false # whether to ignore differences while syncing or not, used when explicitly use ignoredifference feature
