apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debezium-schema-topics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: 'git@github.com:moneYOUnion/dataops-dms.git'
    targetRevision: master
    path: kubernetes/production/schema-topics
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - Validate=true
      - CreateNameSpace=true
      - PruneProgationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false # whether to ignore differences while syncing or not, used when explicitly use ignoredifference feature
