# rbac:
#   serviceAccount:
#     name: cluster-autoscaler
#     annotations:
#       eks.amazonaws.com/role-arn: "{{ your_iam_role_arn }}"

# autoDiscovery:
#   enabled: true
#   clusterName: "{{ your_eks_cluster_name }}"

# clusterName: "{{ your_eks_cluster_name }}"
# awsRegion: "{{ your_region }}"
# vpcId: "{{ your_vpc_id }}"

rbac:
  serviceAccount:
    name: cluster-autoscaler
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::367896522183:role/eks-cluster-autoscaler

autoDiscovery:
  enabled: true
  clusterName: demo-eks

clusterName: demo-eks
awsRegion: eu-central-1
vpcId: vpc-0e8f916ec248057e4