serviceAccount:
  create: true
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::367896522183:role/external-secrets-role

replicaCount: 3
webhook:
  replicaCount: 3

certController:
  replicaCount: 3